catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE')

